In [74]:
import pandas as pd
import dtaidistance.dtw_ndim

In [34]:
ecog = pd.read_csv('../data/ECoG.csv', sep=',')

In [35]:
ecog.head()

ECoG_time  ECoG_ch1  ECoG_ch2  ECoG_ch3  ECoG_ch4  ECoG_ch5  ECoG_ch6  \
0      0.000        48       -60      -174      -226      -123      -308   
1      0.001        40       -87      -208      -256      -115      -350   
2      0.002        46      -113      -210      -248      -124      -365   
3      0.003        78      -112      -181      -220      -116      -368   
4      0.004       109      -115      -178      -216      -128      -342   

   ECoG_ch7  ECoG_ch8  ECoG_ch9  ...  ECoG_ch119  ECoG_ch120  ECoG_ch121  \
0        94        75       -40  ...         -57         174        -229   
1        86        61       -66  ...         -69         170        -229   
2        97        68       -96  ...         -85         139        -213   
3       115       104       -90  ...         -98         103        -213   
4       111       123       -90  ...        -117          70        -218   

   ECoG_ch122  ECoG_ch123  ECoG_ch124  ECoG_ch125  ECoG_ch126  ECoG_ch127  \
0         -84         -40        -292        -264        -206        -269   
1        -101         -42        -256        -265        -231        -258   
2        -102         -11        -230        -248        -230        -217   
3        -127          11        -254        -253        -224        -210   
4        -152          30        -249        -238        -217        -243   

   ECoG_ch128  
0        -286  
1        -310  
2        -301  
3        -299  
4        -274  

[5 rows x 129 columns]

In [36]:
ecog.tail()

ECoG_time  ECoG_ch1  ECoG_ch2  ECoG_ch3  ECoG_ch4  ECoG_ch5  ECoG_ch6  \
663265    663.265        44        47       -41      -111        29       121   
663266    663.266        78        46       -60       -60        50       140   
663267    663.267        67        -1      -103       -29       122       188   
663268    663.268        93       -34      -163       -62       186       261   
663269    663.269       158         1      -142       -35       228       311   

        ECoG_ch7  ECoG_ch8  ECoG_ch9  ...  ECoG_ch119  ECoG_ch120  ECoG_ch121  \
663265       316      -828       116  ...         240         156        -148   
663266       345      -814       121  ...         249         170        -141   
663267       375      -774       122  ...         249         182        -155   
663268       426      -737       135  ...         244         176        -175   
663269       462      -709       165  ...         232         166        -192   

        ECoG_ch122  ECoG_ch123  ECoG_ch124  ECoG_ch125  ECoG_ch126  \
663265        -360        -156        -215          67        -142   
663266        -364        -142        -197          38        -132   
663267        -367        -135        -185          46        -113   
663268        -387        -145        -205          16        -132   
663269        -372        -168        -239         -18        -199   

        ECoG_ch127  ECoG_ch128  
663265          -2        -310  
663266          -3        -373  
663267         -20        -395  
663268         -41        -438  
663269        -146        -495  

[5 rows x 129 columns]

In [37]:
print(df.shape)

(663270, 129)


In [38]:
event = pd.read_csv('../data/Event.csv', sep=',')

In [39]:
event.head()

EventTime  EventData  EventIndex
0      0.000         35           0
1      0.001         40           1
2      0.002         36           2
3      0.003         34           3
4      0.004         35           4

In [40]:
print(df1.shape)

(663270, 3)


In [50]:
prepared = event.EventData <= 100
iti = event[event.EventData.between(300, 400, inclusive=True)] #0
stimulus1 = event[event.EventData.between(650, 750, inclusive=True)] #45
stimulus2 = event[event.EventData.between(950, 1050, inclusive=True)] #90
stimulus3 = event[event.EventData.between(1300, 1400, inclusive=True)] #135
stimulus4 = event[event.EventData.between(1600, 1700, inclusive=True)] #180
stimulus5 = event[event.EventData.between(1950, 2050, inclusive=True)] #225
stimulus6 = event[event.EventData.between(2250, 2350, inclusive=True)] #270
stimulus7 = event[event.EventData.between(2600, 2700, inclusive=True)] #315
stimulus8 = event[event.EventData.between(2900, 3000, inclusive=True)] #360

In [51]:
stimulus1

EventTime  EventData  EventIndex
82015      82.015        686       82015
82016      82.016        692       82016
82017      82.017        684       82017
82018      82.018        685       82018
82019      82.019        691       82019
...           ...        ...         ...
645255    645.255        691      645255
645256    645.256        688      645256
645257    645.257        687      645257
645258    645.258        686      645258
645259    645.259        689      645259

[40072 rows x 3 columns]

[   0- 100] : preparation time before experiment
      [ 300- 400] : ITI
      [ 650- 750] : Stimulus 1 ( 45 degree)
      [ 950-1050] : Stimulus 2 ( 90 degree)
      [1300-1400] : Stimulus 3 (135 degree)
      [1600-1700] : Stimulus 4 (180 degree)
      [1950-2050] : Stimulus 5 (225 degree)
      [2250-2350] : Stimulus 6 (270 degree)
      [2600-2700] : Stimulus 7 (315 degree)
      [2900-3000] : Stimulus 8 (360 degree)

In [59]:
ts1 = ecog.iloc[stimulus1.EventIndex].to_numpy()[:, 1:]
ts2 = ecog.iloc[stimulus2.EventIndex].to_numpy()[:, 1:]
ts3 = ecog.iloc[stimulus3.EventIndex].to_numpy()[:, 1:]
ts4 = ecog.iloc[stimulus4.EventIndex].to_numpy()[:, 1:]
ts5 = ecog.iloc[stimulus5.EventIndex].to_numpy()[:, 1:]
ts6 = ecog.iloc[stimulus6.EventIndex].to_numpy()[:, 1:]
ts7 = ecog.iloc[stimulus7.EventIndex].to_numpy()[:, 1:]
ts8 = ecog.iloc[stimulus8.EventIndex].to_numpy()[:, 1:]

In [60]:
print(ts1.shape, ts2.shape)

(40072, 128) (40119, 128)


In [89]:
def make_experiment(ts1, ts2, len1=100, len2=100):
    t1 = ts1[:len1]
    t2 = ts2[:len2]
    print(t1)
    print(t2)
    #print(dtaidistance.dtw_ndim.warping_paths(t1, t2)[1])
    print(dtaidistance.dtw_ndim.warping_path(t1, t2))
    return dtaidistance.dtw_ndim.warping_path(t1, t2)
    #return dtaidistance.dtw_ndim.distance(t1, t2)
    #dtaidistance.dtw_ndim.distance(t1, t2, window=None, max_dist=None, max_step=None, max_length_diff=None, penalty=None, psi=None, use_c=False)

In [90]:
make_experiment(ts1, ts2)

[[ -36.  188.  324. ...  326.  -38.   23.]
 [ -38.  192.  314. ...  318.   -6.   83.]
 [ -48.  193.  298. ...  310.    9.  133.]
 ...
 [  94.  199.  -72. ...  -28. -284. -166.]
 [  44.  172.  -96. ...   -4. -295. -135.]
 [ -11.  149. -123. ...  -18. -267.  -75.]]
[[ -64. -143.   64. ... -117. -183. -249.]
 [ -34. -100.   64. ... -108. -179. -258.]
 [ -30.  -44.  122. ...  -73. -151. -279.]
 ...
 [-264.  343.  184. ...  394. -316. -526.]
 [-279.  305.  117. ...  365. -337. -520.]
 [-296.  294.  116. ...  408. -323. -450.]]


AttributeError: module 'dtaidistance.dtw_ndim' has no attribute 'warping_path'